<?php
require_once __DIR__ . '/config/bootstrap.php';
require_login($auth);

// type=client (default, backward compatible with existing links that
// omit it) or type=case — picks which document library + upload root
// to serve from. Everything else about the flow is identical.
$type = ($_GET['type'] ?? 'client') === 'case' ? 'case' : 'client';
$docId = (int)($_GET['doc'] ?? 0);
if ($docId <= 0) {
    http_response_code(404);
    exit('Document not found.');
}

if ($type === 'case') {
    $table = 'legalops_case_documents';
    $ownerCol = 'case_id';
    $uploadDir = CASE_UPLOAD_DIR;
} else {
    $table = 'legalops_client_documents';
    $ownerCol = 'client_id';
    $uploadDir = UPLOAD_DIR;
}

$stmt = $pdo->prepare("SELECT * FROM {$table} WHERE id = ?");
$stmt->execute([$docId]);
$doc = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$doc) {
    http_response_code(404);
    exit('Document not found.');
}

$path = rtrim($uploadDir, '/') . '/' . $doc[$ownerCol] . '/' . $doc['stored_name'];

// Defence in depth: stored_name is generated by us (hex + known extension)
// so this can't traverse out of the owner's folder, but double check the
// resolved path is still inside the upload root before touching the
// filesystem.
$realBase = realpath($uploadDir);
$realPath = realpath($path);
if (!$realBase || !$realPath || strpos($realPath, $realBase) !== 0 || !is_file($realPath)) {
    http_response_code(404);
    exit('Document not found on disk.');
}

header('Content-Type: ' . ($doc['mime_type'] ?: 'application/octet-stream'));
header('Content-Disposition: inline; filename="' . basename($doc['original_name']) . '"');
header('Content-Length: ' . filesize($realPath));
header('X-Content-Type-Options: nosniff');
readfile($realPath);
