<?php
require_once __DIR__ . '/config/bootstrap.php';
require_login($auth);

$docId = (int)($_GET['doc'] ?? 0);
if ($docId <= 0) {
    http_response_code(404);
    exit('Document not found.');
}

$stmt = $pdo->prepare('SELECT * FROM legalops_client_documents WHERE id = ?');
$stmt->execute([$docId]);
$doc = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$doc) {
    http_response_code(404);
    exit('Document not found.');
}

$path = rtrim(UPLOAD_DIR, '/') . '/' . $doc['client_id'] . '/' . $doc['stored_name'];

// Defence in depth: stored_name is generated by us (hex + known extension)
// so this can't traverse out of the client's folder, but double check the
// resolved path is still inside UPLOAD_DIR before touching the filesystem.
$realBase = realpath(UPLOAD_DIR);
$realPath = realpath($path);
if (!$realBase || !$realPath || strpos($realPath, $realBase) !== 0 || !is_file($realPath)) {
    http_response_code(404);
    exit('Document not found on disk.');
}

header('Content-Type: ' . ($doc['mime_type'] ?: 'application/octet-stream'));
header('Content-Disposition: inline; filename="' . basename($doc['original_name']) . '"');
header('Content-Length: ' . filesize($realPath));
header('X-Content-Type-Options: nosniff');
readfile($realPath);
